/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Antdtest: typeof import('./src/components/Antdtest.vue')['default']
    Authentication: typeof import('./src/components/Authentication.vue')['default']
    Child: typeof import('./src/components/child.vue')['default']
    ElementTest: typeof import('./src/components/elementTest.vue')['default']
    EventLoop: typeof import('./src/components/eventLoop.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    MoveBox: typeof import('./src/components/moveBox.vue')['default']
    Parent: typeof import('./src/components/parent.vue')['default']
    PiniaTest: typeof import('./src/components/PiniaTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTest: typeof import('./src/components/routerTest.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    ToBase64: typeof import('./src/components/toBase64.vue')['default']
  }
}
